version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          key: nsfminer-{{ .Environment.CACHE_VERSION }}


  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ~/.hunter
          key: nsfminer-{{ .Environment.CACHE_VERSION }}

  build:
    steps:
      - run: ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
      - run: apt update
      - run: apt install -y apt-transport-https ca-certificates gnupg software-properties-common wget
      - run: wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
      - run: apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' -y
      - run: apt install -y git cmake mesa-common-dev libdbus-1-dev
      - run: apt update
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache_cmd
      - run: cmake -DHUNTER_JOBS_NUMBER=4 -H. -Bbuild
      - run: cmake --build build -- -j4
      - save_cache_cmd
      - store_artifacts:
          path: build/nsfminer/nsfminer
          destination: nsfminer

executors:
 docker-executor-u1804n11:
   docker:
     - image: nvidia/cuda:11.0-devel-ubuntu18.04

jobs:
  build-with-docker-u1804n11:
    executor: docker-executor-u1804n11
    steps:
      - build
    environment:
        TZ: "America/New_York"
  resource_class: xlarge

workflows:
  build-with-docker:
    jobs:
      - build-with-docker-u1804n11
